version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
       - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

  laravel:
     image: hobord/php-fpm-laravel:dev-7.2.2
     # restart: always
     volumes:
       - ./:/var/www/html
     links:
       - mysql
       # - redis
     depends_on:
       - mysql
       # - redis
     environment:
       DB_HOST: mysql
       DB_PORT: 3306
       DB_DATABASE: laravel
       DB_USERNAME: laravel
       DB_PASSWORD: laravel
#       XDEBUG_CONFIG: "remote_host=192.168.99.1"
#       XDEBUG_SESSION_START: phpstorm-xdebug

  nginx:
     build:
       context: './'
       dockerfile: ./nginx/Dockerfile
     volumes:
       - './:/var/www/html'
     environment:
       NGINX_LISTEN: '80'
       FCGI_SERVER: laravel
       FCGI_PORT: '9000'
     ports:
       - '80:80'
     links:
       - laravel
     depends_on:
       - laravel

  # redis:
  #   image: redis

  # redis_commander:
  #   image: tenstartups/redis-commander
  #   depends_on:
  #     - redis
  #   command: --redis-host redis
  #   links:
  #     - redis:redis
  #   ports:
  #     - "8082:8081"

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   restart: always

  # mongoclient:
  #   image: mongoclient/mongoclient
  #   depends_on:
  #     - mongodb
  #   links:
  #     - mongodb
  #   ports:
  #     - "8083:3000"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   environment:
  #     discovery.type: single-node

  # # vim /etc/sysctl/sysctl.conf -> vm.max_map_count = 262144
  # # username and pasword-> elastic:changeme
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:5.6.3
  #   depends_on:
  #     - elasticsearch
  #   links:
  #     - elasticsearch
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - "ELASTICSEARCH_URL=http://elasticsearch:9200"

volumes:
    db_data:
#    esdata:
